define({  
   "item":{  
      "title":"Default Scene",
      "type":"Web Scene",
      "typeKeywords":[  
         "3D",
         "Map",
         "Scene",
         "Streaming",
         "Web",
         "Web Scene"
      ],
      "description":null,
      "tags":[  
         "scene"
      ],
      "snippet":null,
      "thumbnail":"thumbnail/ago_downloaded.png",
      "documentation":null,
      "extent":[  

      ],
      "spatialReference":null,
      "accessInformation":null,
      "licenseInfo":null,
      "culture":"en",
      "properties":null,
      "url":null,
      "access":"public",
      "size":1036,
      "appCategories":[  

      ],
      "industries":[  

      ],
      "languages":[  

      ],
      "largeThumbnail":null,
      "banner":null,
      "screenshots":[  

      ],
      "listed":false,
      "ownerFolder":null,
      "commentsEnabled":true,
      "numComments":0,
      "numRatings":0,
      "avgRating":0,
      "numViews":0
   },
   "itemData":{  
      "operationalLayers":[  

      ],
      "baseMap":{  
         "id":"151030b5706-basemap-1",
         "title":"Topographic",
         "baseMapLayers":[  
            {  
               "id":"151030b56f5-layer-4",
               "url":"http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",
               "layerType":"ArcGISTiledMapServiceLayer"
            }
         ],
         "elevationLayers":[  
            {  
               "id":"globalElevation",
               "url":"http://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer",
               "layerType":"ArcGISTiledElevationServiceLayer"
            }
         ],
         "transparency":0
      },
      "version":"1.2",
      "authoringApp":"WebSceneViewer",
      "authoringAppVersion":"3.9.0.0",
      "initialState":{  
         "viewpoint":{  
            "scale":76334275.54889014,
            "rotation":8.537736562175269e-7,
            "targetGeometry":{  
               "x":0,
               "y":-0.0033830021156527556,
               "spatialReference":{  
                  "wkid":102100,
                  "latestWkid":3857
               },
               "z":-0.00009191036224365234
            },
            "camera":{  
               "position":{  
                  "x":0,
                  "y":-44528.29407777666,
                  "spatialReference":{  
                     "wkid":102100,
                     "latestWkid":3857
                  },
                  "z":25512548.000000004
               },
               "heading":359.99999914622634,
               "tilt":0.0999987746471044
            }
         },
         "environment":{  
            "lighting":{  
               "displayUTCOffset":0
            }
         }
      },
      "presentation":{  
         "slides":[  

         ]
      }
   }
});